version: '3'
services:
  brat:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: cassj/brat
    container_name: brat_annotation
    volumes:
      - "./brat-data:/bratdata"
      - "./brat-cfg:/bratcfg"
    environment:
      - BRAT_USERNAME=admin
      - BRAT_PASSWORD=admin
      - BRAT_EMAIL=brat@example.com
    ports:
      - "8080:80"

#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.brat.rule=Host(`${DOMAIN}`) && PathPrefix(`/brat`)"
#      - "traefik.http.routers.brat.entrypoints=webs"
#      - "traefik.http.routers.brat.tls=true"
#      - "traefik.http.routers.brat.service=brat-service"
#      - "traefik.http.services.brat-service.loadbalancer.server.port=80"
#      - "traefik.http.middlewares.test.stripprefix.prefixes=/brat"
#      - "traefik.http.routers.brat.middlewares=test"

#networks:
#  default:
#    name: traefik_net
#    external: true
